### ISSUE TITLE
First release TODO

### ISSUE THREAD

**Issue by daniellee** [grafana/azure-monitor-datasource#7]
- [x] installation instructions for an Azure user
- [x] README.md needs to be completed
- [x] Logo (temporary logo in place but need a 100x100 image)
- [x] Change Config page help hover text from placeholders to real information.
